version: "2"
services:
  app:
    depends_on:
      - postgres
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - SECRET_KEY_BASE
      - DATABASE_URL=postgres://postgres:postgres@postgres/guitar_store_dev
      - IS_LOCAL=true
    ports:
      - 4000:4000

  postgres:
    image: postgres:10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=guitar_store_dev
    ports:
      - 5432:5432
